# -*- coding: utf-8 -*-
"""Itransition_task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NnFU4Hu9LcCQ2tyVKHw0c2jmxQwZX7Mg
"""

#Solution of Task-01
def max_multiplication(s):
    if not isinstance(s, str):
        return 'nil'

    max_product = 0

    for i in range(len(s) - 3):
        if s[i:i + 4].isdigit():
            product = int(s[i]) * int(s[i + 1]) * int(s[i + 2]) * int(s[i + 3])
            max_product = max(max_product, product)

    if max_product > 0:
        return max_product
    else:
        return 'nil'

print(max_multiplication('abc12345def'))
print(max_multiplication('a1b2c3d4e'))

